### ISSUE TITLE
Configure Vercel for PR previews and a "demo" site

### ISSUE THREAD

**Issue by mcollina** [nodejs/undici-website#3]
as titled

**Comment by Ethan-Arrowood** [comment]
Let's look at how the Node site is set up on Vercel. What's the account, etc. Then we should configure that here too. I can help with that.

**Comment by mcollina** [comment]
Let's do that? Should we ask @nodejs/build for access to our Vercel account?

**Comment by targos** [comment]
I'm not aware that the build WG has access to it. I can't find it in the secrets repo.

**Comment by MoLow** [comment]
> I'm not aware that the build WG has access to it. I can't find it in the secrets repo.

it should probably be added there. /CC @nodejs/nodejs-website @ovflowd

**Comment by ovflowd** [comment]
> > I'm not aware that the build WG has access to it. I can't find it in the secrets repo.
> 
> it should probably be added there. /CC @nodejs/nodejs-website @ovflowd

Let me check where our Cloudflare is pointing at. BTW @MoLow the right tag is @nodejs/web-infra

**Comment by ovflowd** [comment]
Okay, this is being served on GitHub Pages, but GitHub Pages seems to be disabled within this repo?

![image](https://github.com/nodejs/undici-website/assets/12037269/7cdf49bb-bec7-4f4e-a87b-6469c738d40f)

**Comment by ovflowd** [comment]
Alrighty, it comes from the `undici` repository

![image](https://github.com/nodejs/undici-website/assets/12037269/699ba394-cd3a-4c80-89bb-5cd8f79941f7)

**Comment by ovflowd** [comment]
@mcollina we can setup Vercel for this repository, but we need the source to be added here. What sort of Framework are talking about, or some static pages?

**Comment by AugustinMauroy** [comment]
@ovflowd take a look to #2

**Comment by ovflowd** [comment]
> @ovflowd take a look to #2

Thanks, Augustin!

**Comment by mcollina** [comment]
I didn't mean to change `undici.nodejs.org` to Vercel. Let's do that once the new website is built.

We just need _this_ repository added on the Node.js Vercel account.

**Comment by mcollina** [comment]
@nodejs/tsc @targos who has access to the Vercel account?

**Comment by ovflowd** [comment]
> @nodejs/tsc @targos who has access to the Vercel account?

Web Infra and Build WG should have access. Ill add this repository there :)

**Comment by ovflowd** [comment]
> I didn't mean to change `undici.nodejs.org` to Vercel. Let's do that once the new website is built.
> 
> 
> 
> We just need _this_ repository added on the Node.js Vercel account.

Ah!

**Comment by richardlau** [comment]
> > @nodejs/tsc @targos who has access to the Vercel account?
> 
> Web Infra and Build WG should have access. Ill add this repository there :)

I'm not sure that's true that Build WG has access. AFAIK we're using individual accounts to manage Vercel (instead of, for example, an account owned by the Build WG (i.e. user/password details in Build's secrets repository)). I think my account was added (but I'm not the entire Build WG 😛).

**Comment by ovflowd** [comment]
> > > @nodejs/tsc @targos who has access to the Vercel account?
> > 
> > 
> > Web Infra and Build WG should have access. Ill add this repository there :)
> 
> I'm not sure that's true that Build WG has access. AFAIK we're using individual accounts to manage Vercel (instead of, for example, an account owned by the Build WG (i.e. user/password details in Build's secrets repository)). I think my account was added (but I'm not the entire Build WG 😛).

Afaik we created a shared account within Node.js 1Password. Could you double check? :)

**Comment by ovflowd** [comment]
@mcollina 

- I've invited the Vercel Application for this repository within the Node.js org (cc @nodejs/tsc I used my Administrator powers on behalf of @mcollina)
- I've added the shared Node.js Vercel account as an administrator within this repository (cc @nodejs/tsc I used my Administrator powers on behalf of @mcollina)
- I've added the project within Vercel at the OpenJS's Infrastructure
- I've set the default branch for the time being to Ethan's Draft Branch
- I've triggered a deployment
- Live on https://undici-website.vercel.app/

**Comment by richardlau** [comment]
> > > > @nodejs/tsc @targos who has access to the Vercel account?
> > > 
> > > 
> > > Web Infra and Build WG should have access. Ill add this repository there :)
> > 
> > 
> > I'm not sure that's true that Build WG has access. AFAIK we're using individual accounts to manage Vercel (instead of, for example, an account owned by the Build WG (i.e. user/password details in Build's secrets repository)). I think my account was added (but I'm not the entire Build WG 😛).
> 
> Afaik we created a shared account within Node.js 1Password. Could you double check? :)

I don't have access to 1Password. Also that isn't part of the Build WG.

**Comment by ovflowd** [comment]
> > > > > @nodejs/tsc @targos who has access to the Vercel account?
> > > > 
> > > > 
> > > > Web Infra and Build WG should have access. Ill add this repository there :)
> > > 
> > > 
> > > I'm not sure that's true that Build WG has access. AFAIK we're using individual accounts to manage Vercel (instead of, for example, an account owned by the Build WG (i.e. user/password details in Build's secrets repository)). I think my account was added (but I'm not the entire Build WG 😛).
> > 
> > 
> > Afaik we created a shared account within Node.js 1Password. Could you double check? :)
> 
> I don't have access to 1Password. Also that isn't part of the Build WG.

I thought all Build WG members had access to 1Password + the TSC... I'm more than happy sharing these credentials or finding an alternative place for them to live 🙇

**Comment by mhdawson** [comment]
All TSC members should/can have access to 1password. We can also set up a 1 password vault that all build WG members have access to, however, that is not the way the build WG shares most of the credentials it manages.

I think it comes down to what the existing build WG members would prefer.  1password might be easier to manage especially if we want shared access with some people outside of the build WG, but it would be another location/place that build WG members would have to join.  @nodejs/build preferences?

**Comment by mcollina** [comment]
Closing this, it's done!

**Comment by ovflowd** [comment]
> All TSC members should/can have access to 1password. We can also set up a 1 password vault that all build WG members have access to, however, that is not the way the build WG shares most of the credentials it manages.
> 
> I think it comes down to what the existing build WG members would prefer. 1password might be easier to manage especially if we want shared access with some people outside of the build WG, but it would be another location/place that build WG members would have to join. @nodejs/build preferences?

bump cc @nodejs/build
